version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "18:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.41
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.0
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.1
    - 13.0.10
    - 13.0.15
    - 13.0.2
    - 13.0.5
    - 13.0.7
    - 13.1.2
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
    - 17.0.3
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.9
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
  - dependency-name: node-notifier
    versions:
    - 8.0.1
  - dependency-name: react-scripts
    versions:
    - 4.0.1
